### ISSUE TITLE
create-graphql init Spawn error

### ISSUE THREAD

**Issue by nic** [lucasbento/create-graphql#64]
$  create-graphql init AwesomeProject

✓ GraphQL project AwesomeProject created.
⠋ Creating a new GraphQL project...events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarn ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

<img width="630" alt="captura de tela 2017-02-07 as 11 54 50" src="https://cloud.githubusercontent.com/assets/66042/22693899/47b005ce-ed2c-11e6-8105-0de96bb0e63c.png">

Any idea?

**Comment by lucasbento** [comment]
@nic: it seems to be throwing an error here: https://github.com/lucasbento/create-graphql/blob/master/packages/generator/src/app/index.js#L80-L89.

Which yarn version are using?

**Comment by felippepuhle** [comment]
Yesterday I was experiencing something like this and Yarn wasn't at my Path variable.

**Comment by lucasbento** [comment]
@felippepuhle: but you were still able to use it through your terminal?

**Comment by felippepuhle** [comment]
After adding Yarn to Path, the init command works perfectly here.

**Comment by lucasbento** [comment]
Hmm, the way the current code does is just run a `which yarn` to check if it is installed and simply hit `yarn` if it is, I think it's better to get yarn's bin file path than depend on it being or not on PATH.

**Comment by sibelius** [comment]
so, this bug happens when `yarn` is not installed

@nic @felippepuhle could u guys send a PR fixing this please?

**Comment by lucasbento** [comment]
@felippepuhle's problem appears to be different than @nic's.

The problem is when its not specified on the machine's PATH variable which makes it unaccessible through a global command. 

My guess would be to run the binary [here](https://github.com/lucasbento/create-graphql/blob/master/packages/generator/src/app/index.js#L81) using `shell.which('yarn')` which probably returns its path if found.

Also, [this](https://github.com/lucasbento/create-graphql/blob/master/packages/generator/src/app/index.js#L84) condition seems to be wrong, should probably be `if (!shell.which('yarn')) {` so it uses `npm` if `yarn` is not available which then fixes @nic's issue.

@nic, @felippepuhle: would love if you guys could help sending a PR for it.

**Comment by felippepuhle** [comment]
Working on it! 😄

**Comment by sibelius** [comment]
fixed!

**Comment by sibelius** [comment]
@nic reopen if the error continues

**Comment by nic** [comment]
@lucasbento @sibelius @felippepuhle Now it works!! Thanks a lot guys!

<img width="428" alt="captura de tela 2017-02-07 as 23 51 25" src="https://cloud.githubusercontent.com/assets/66042/22720174/71fae8b2-ed90-11e6-9861-0e10b96b4acc.png">
